### ISSUE TITLE
Index out of range exception if the boundary was detected at the end of a file, but the end of the boundary is outside of the current buffer

### ISSUE THREAD

**Issue by ProperIT** [Vodurden/Http-Multipart-Data-Parser#16]
Hello,

thank you very much for great solution!
I used it to upload about a million files in SharePoint.
it worked for most of the files, but sometimes I stumbled upon an "Index out of range" exception in the CalculateNewlineLength method at line 372 in MultipartFormDataParser.cs.

The reason for this exception was that the length of the byte array variable "data", which is the currently buffered part of the file stream, was smaller than the value of the variable "offset".
This error can be reproduced, if a boundary between a file stream and the metadata or another file is detected at the end of the current buffer (the variable "fullBuffer" in the method "ParseFilePart"), but the end of the boundary is outside of the buffer.

In order to fix this I changed the line 506 in MultipartFormDataParser.cs to:
if (endPos != -1 && fullBuffer.Length > endPos + endPosLength + 2)
Here I make sure, that the end of the boundary is inside the current buffer.

Has someone else seen this error? 
Can you please verify the issue and apply the fix?

Thanks.

**Comment by Vodurden** [comment]
Hi Everyone.

I haven't provided a fix for this issue but I wonder if it's related to https://github.com/Vodurden/Http-Multipart-Data-Parser/pull/20 which has been fixed by otf. If you've still got this issue would you mind testing if it still occurs on the latest version to see if it's a separate issue?

Thanks!

**Comment by ProperIT** [comment]
Hi Jake,

the fix addresses the same issue that I had (an exception in the Method "CalculateNewlineLength" regarding fullBuffer length and boundary position).
Unfortunately I couldn't investigate the problem further or write a unit test, because the project in which I used the parser was canceled. That's why I cannot confirm that the fix by otf resolves my problem, but I am pretty sure it does.

Regards,
ProperIT

**Comment by Vodurden** [comment]
That's good to hear! (Sorry about the project though). I'll close the issue.

Thanks again for your contributions.

**Comment by RNenad** [comment]
Hello,
thanks for the great solution.
I have encountered the same problem. Situation is following: endBoundary is cutted by the end of current chunk exactly in a way that last "--" are missing, so it appears like boundary is found. Then next part contains only "--", which causes the problems.
Solution is following: when we find boundary exactly at the end of currentBuffer (end of combined buffer), we should ignore it, read next buffer and search again (then we will find endBoundary, which is correct):
in method ParseFilePart(...)
...
				else if (boundaryPos >= 0 && endBoundaryPos < 0)
				{
					//NR:if we found boundary and boundary is exactly at the end of buffer, we don't know if is boundary or partial endBoundary, so we will read one more buffer
					if (boundaryPos + boundaryLength != prevLength + curLength)
					{
						// Select boundary    
						endPos = boundaryPos;
						endPosLength = boundaryLength;
					}
				}
...

It is really funny how this rare case could happen :).

Thanks,
Nenad.

**Comment by roqz** [comment]
I am still experiencing the behavior described in the first post. the following change fixed it for me:

private int CalculateNewlineLength(ref byte[] data, int offset)
		{
			byte[][] newlinePatterns = { Encoding.GetBytes("\r\n"), Encoding.GetBytes("\n") };

			// Go through each pattern and find which one matches.
			foreach(var pattern in newlinePatterns)
			{
				bool found = false;
				for(int i = 0; i < pattern.Length; ++i)
				{
					// change: check if array length is long enough:
					if(data.Length <= offset + i || pattern[i] != data[offset + i])
					{
						found = false;
						break;
					}

					found = true;					
				}

				if(found)
				{
					return pattern.Length;
				}
			}

			return 0;
		}

**Comment by Vodurden** [comment]
@RNenad, @roqz. Going through the old issues it seems I let these comments slip through the cracks. Sorry about that!

@RNenad I just committed a change that is functionally identical to the one you proposed and has fixed the issue. I really do appreciate your contribution and I could have saved myself a good chunk of time if I'd remembered that this thread existed so thanks for contributing! :)

I'm not sure if either of you are still using this library but if you are version 2.1.1 has a fix functionally identical to @RNenad's solution included in it's change set.

Thanks!
