### ISSUE TITLE
parsing failure

### ISSUE THREAD

**Issue by otf** [Vodurden/Http-Multipart-Data-Parser#19]
this test case is fail.

https://github.com/otf/Http-Multipart-Data-Parser/commit/158df5f49daad5050885709cbf68a94d175721e0#diff-f73660006b84fe1ba8d9d28a80166b1fR46

**Comment by Vodurden** [comment]
Closed by merging https://github.com/Vodurden/Http-Multipart-Data-Parser/pull/20

Thanks again!
