### ISSUE TITLE
Latest version doesn't give you the files

### ISSUE THREAD

**Issue by senikk** [Vodurden/Http-Multipart-Data-Parser#22]
The files should be in the "Files" not just internally in "var files" which hasn't changed from Dictionary type to List.

**Comment by Vodurden** [comment]
Ah you're right! This actually reveals that the testing code is incorrect in this case and will require some extra time to verify that the tests are actually testing. I'll look at it ASAP when I get home tonight and fix it then.

**Comment by Vodurden** [comment]
Fixed by https://github.com/Vodurden/Http-Multipart-Data-Parser/commit/2f17700c97ca799428ec250945b3c4ed8d660bdd. It also revealed that the unit tests were flawed if the parser returned no files which I have fixed.

Thanks for your contribution!
