### ISSUE TITLE
Issues when parsing files being uploaded across network

### ISSUE THREAD

**Issue by tttito2** [Vodurden/Http-Multipart-Data-Parser#26]
First off awesome project!

I am using the parser in a vb.net application that has a self hosted webserver. I am using it to parse out uploaded text files. Each text file is very small 1-4kb. I am uploading multiple files at a time and sometimes upwards of 10-15 files at once. When selecting files from my local machine everything is parsed flawlessly however, if I select files from across a network, I receive the debug assert as shown below and nothing is parsed. As I stated, these files are very small, and even combined, the total file size is less than 50kb. In the snippet below, bodyData is a byte array and regardless of whether the files are being uploaded locally or coming from across the network, the byte array is the same size. So, it seems that the same amount of data is there to be parsed. Do you have any suggestions?

Dim stream As New MemoryStream(bodyData)
Dim parser As New MultipartFormDataParser(stream)

If parser.Files.Count > 0 Then
    For Each f In parser.Files
        Using fileStream = File.Create(mDir & f.FileName)
            f.Data.Seek(0, SeekOrigin.Begin)
            f.Data.CopyTo(fileStream)
            fileStream.Close()
        End Using
    Next
End If

![debug](https://cloud.githubusercontent.com/assets/11578238/6760783/697d8106-cf22-11e4-8bba-eb9e77b91e4c.PNG)

**Comment by Vodurden** [comment]
Hi tttito2.

This occurs when the buffer we're using for parsing is smaller then the multipart boundary. Either something is making the buffer too small or the boundary detection is failing. 

Unfortunately I don't have enough context from just this issue. One thing you could try is manually setting the boundary with the Multipart Constructor and then running it on your file to see if that makes a difference. If it does it means the boundary is auto-detecting incorrectly. 

Alternatively if you can provide any extra context (code, data, etc...) I'll try to help further.

**Comment by tttito2** [comment]
Thanks for the quick response! Unfortunately (or maybe I should say fortunately...), I am not able to recreate the issues that I was having on Friday. Uploads from anywhere on the network are being parsed as they should.

**Comment by Vodurden** [comment]
I'm glad the issue is resolved. Don't hesitate to contact me if it (or any other issue) resurfaces.
