### ISSUE TITLE
Version 1.1.5 was not published

### ISSUE THREAD

**Issue by SommerEngineering** [Vodurden/Http-Multipart-Data-Parser#27]
Dear all,

The version 1.1.5 was not published to NuGet: https://www.nuget.org/packages/HttpMultipartParser/ Please consider to publish also 1.1.5 to NuGet :)

Best regards,
Thorsten

**Comment by Vodurden** [comment]
Oops! I uploaded it but forgot to verify. The NuGet package is now updated.

Thanks!
