### ISSUE TITLE
IIS Worker stuck in a loop....

### ISSUE THREAD

**Issue by BDvirus** [Vodurden/Http-Multipart-Data-Parser#29]
Hi Vodurden,
Thanks for the great Http-Multipart-Data-Parser..

Assuming we forget to close the boundary..
for example:

curl -X POST -H "Content-Type: multipart/form-data; --00content0boundary00" --data-binary @my2.txt http://localhost/Service1.svc/SomeMethod

The content of my2.txt is:
--00content0boundary00
Content-Disposition: form-data; name="A"

123
--00content0boundary00
Content-Disposition: form-data; name="B"

this is B
--00content0boundary00
Content-Disposition: form-data; name="C"

Bili
--00content0boundary00

for some reason it's stuck in a loop... and the IIS Worker memory usage as expected.. leak.

**Comment by Vodurden** [comment]
Hi BDvirus

Thanks for submitting this issue. I haven't got time to immediately fix this issue but I'll get on it within a week or so. I have a pretty good idea of where this could be occurring. 

Thanks!

**Comment by harsimranb** [comment]
I'm also having this issue.

**Comment by Vodurden** [comment]
Sorry this took me so long to get around to! Life unfortunately got in the way :(

Anyway. I've just submitted version 2.0.1 which should fix the issue. The relevant commit is here: https://github.com/Vodurden/Http-Multipart-Data-Parser/commit/bf1fdd14649c57b6e3ec1136ba31b4f3544cecef

I opted to consider this an error rather then tolerating the input but it shouldn't cause any infinite loops anymore.

Please let me know if you're still experiencing the issue after upgrading! I'll leave this open for a little bit to let everyone confirm. Afterwards I'll close the issue.
