### ISSUE TITLE
Optimizing parsing speed

### ISSUE THREAD

**Issue by catester** [Vodurden/Http-Multipart-Data-Parser#3]
Hi Jake,
Thanks for your efforts in creating this great parser, it's really well designed.
I have some suggestions though:

- When I read this on the description: "This particular parser is well suited to parsing large data from streams as it doesn't attempt to read the entire stream at once and procudes a set of streams for file data.", I was glad that at last I found a parser which doesn't store all the data in memory. However I was surprised when I saw you were storing the resulting file data in a MemoryStream at ParseFilePart method. In my opinion, this kills the premise. No big deal though, I implemented an interface and integrated it with the parser to call methods like BeginFile, WriteData, EndFile when necessary. This way I can redirect the stream whereever I want without any memory pressure on the server. This is especially good for large files (> 2GB).

- Do you think the parser can be optimized further? On my local tests, I can see 20 Mb/s with the parser which is not bad but when I upload via pure stream (chunked though) I can see 200 Mb/s to 300 Mb/s. Note that these speed tests exclude processing the file, i.e. writing to disk. I used a buffer size of 80kb. I came along the below post which discusses parsing file uploads at 500 mb/s:
http://debuggable.com/posts/parsing-file-uploads-at-500-mb-s-with-node-js:4c03862e-351c-4faa-bb67-4365cbdd56cb
If they can do this with node.js , we should be able to do it better with C# :) I know you are using KMP Algorithm and the poster seems to be using Boyer-Moore algorithm with an additional trick.

Let me know.

**Comment by Vodurden** [comment]
Hi ueberboss.

I know this issue has been around for a while and I'm sorry it's taken me so long to look at it. I've changed the substring parsing algorithm such that it reflects the observations pointed out in the article you referenced (http://debuggable.com/posts/parsing-file-uploads-at-500-mb-s-with-node-js:4c03862e-351c-4faa-bb67-4365cbdd56cb). The changes are included in version 1.1.1 and should see significant speed ups in the parsing of large files.

If you're still using the parser let me know if you see any improvements!

Either way thanks for your help and sorry for the enormous delay!

**Comment by ueberboss** [comment]
Hi Vodurden,

thanks for the update!  Unfortunately my side-project has made little progress, but I have not halted work on it and have been following your project here.  I will be merging in the latest of your changes.  It was catester who mentioned the article - hopefully he/she can report on a performance improvement.

Thanks again for all your work on a core component!

**Comment by Vodurden** [comment]
Whoops! I forgot to read the entire thread for names. Thanks to both of you for contributing! Hopefully the improvements help catester as well!

**Comment by catester** [comment]
Hi Jake,
Thanks for the algorithm improvement. I can see a speed increase of 5x to 6x with this change so it's pretty good. However during my testing I experienced heavy CPU usage (even throttling/freezing), I am not sure if it's related directly to the parser though. It's probably something about my environment. I will check if same thing happens with the old algorithm too.

**Comment by catester** [comment]
I examined and fixed the problem: 78b453d96cccc64a0ab68dc48dc679684ea25c0d
