### ISSUE TITLE
Stream.Null cannot be constructed

### ISSUE THREAD

**Issue by dizzleuk** [Vodurden/Http-Multipart-Data-Parser#32]
private MultipartFormDataParser p_data = new MultipartFormDataParser(Stream.Null);

Causes an exception to be thrown, I only downloaded the library about 10 minutes ago but figured I can bug report this as its quite good practice to check for null values. Maybe it should work this way by design please let me know.

**Comment by Vodurden** [comment]
Hi dizzleuk. Thanks for your feedback!

I agree with your suggestions so I've gone ahead and implemented them. They're available in the 2.1.1 version of the library and the relevant commit is here: https://github.com/Vodurden/Http-Multipart-Data-Parser/commit/86e53ad87f2c780e1e7e3ca2df2b55f44bd5a01f

I'm going to go ahead and close this but feel free to comment if you feel there's more to the discussion :)

Thanks again!
