### ISSUE TITLE
Multipartformparser is throwing "index was outside the bounds of the array " exception

### ISSUE THREAD

**Issue by jyothi888** [Vodurden/Http-Multipart-Data-Parser#36]
Hi 

Iam using Multipartformparser to read two PDF's from HTTP post request but on the below line its throwing index was outside the bounds of the array error.

dim parser=New Multipartformparser (stream)

Please advise ..will be of great help..

**Comment by Vodurden** [comment]
Hi jyothi888

Thanks for submitting an issue!

Unfortunately without more information I can't begin diagnosing this issue. Could you include a Stack Trace from the error and if possible a text representation of the multipart data you're parsing?

Thanks!

**Comment by jyothi888** [comment]
Thanku for the response..

CALL METHOD l_o_multipart->set_header_field
        EXPORTING
          name  = 'content-disposition'
          value = 'form-data; name="content"; filename="FILE1";'.
* Set the content type
      CALL METHOD l_o_multipart->set_content_type
        EXPORTING
          content_type = 'application/pdf; charset=utf-8'. 
*Set File 2
    l_o_multipart ?=  l_o_client->request->if_http_entity~add_multipart( ).
    IF l_o_multipart IS BOUND.

      CALL METHOD l_o_multipart->set_header_field
        EXPORTING
          name  = 'content-disposition'
          value = 'form-data; name="content"; filename="FILE2";'.
* Set the content type
      CALL METHOD l_o_multipart->set_content_type
        EXPORTING

This is the post request.

we have get those files and merge them...

**Comment by Vodurden** [comment]
Hi jyothi888.

Thanks for posting a sample!

I've merged https://github.com/Vodurden/Http-Multipart-Data-Parser/issues/35 into master and released version `2.1.2` of the library. Try upgrading the package and see if that solves the issue :)
