### ISSUE TITLE
Sample implementation code for StreamingMultipartFormDataParser

### ISSUE THREAD

**Issue by rajkumar-qsg** [Vodurden/Http-Multipart-Data-Parser#42]
Hi, i am using "MultipartFormDataParser" class for uploading files from my wcf service (c#).  I am getting out of memory exception for large files and i have decided to use "StreamingMultipartFormDataParser".  But i am little confused with implementation.  Can you please share a sample code implementing this class.

**Comment by Vodurden** [comment]
Hi rajkumar. Included in the README is a handy example:

```
var parser = new StreamingMultipartFormDataParser(stream);
parser.ParameterHandler += parameter => DoSomethingWithParameter(parameter);
parser.FileHandler += (name, fileName, type, disposition, buffer, bytes) =>
{
    // Write the part of the file we've recieved to a file stream. (Or do something else)
    // Assume that filesreamsByName is a Dictionary<string, FileStream> of all the files
    // we are writing.
    filestreamsByName[name].Write(buffer, 0, bytes);
};
parser.StreamClosedHandler += () 
{
    // Do things when my input stream is closed
};
```

The basic idea is that you need to register a `ParameterHandler` and `FileHandler` event handler function which will be passed the inputs as they are streamed in. Let me know if you need further help.

**Comment by rajkumar-qsg** [comment]
Thank you for your quick response.  When we tried implementing your sample, we are getting error "Operation '+=' cannot be applied to operands of type ...........and 'lambda expression'".

I am sharing below the sample code that we are using currently using "MultiPartFormDataParser", can you please help us in explaining how to convert the same and implement using  'StreamingMultipartFormDataParser'.


IncomingWebRequestContext IncWebReqContext = WebOperationContext.Current.IncomingRequest;
string fileName = IncWebReqContext.Headers["FileName"];

 MultipartFormDataParser parser = new MultipartFormDataParser(InputFileStream);

using (FileStream fs = new FileStream(HostingEnvironment.ApplicationPhysicalPath + "Uploads\\" + fileName, FileMode.Create, FileAccess.ReadWrite, FileShare.ReadWrite))
{
    const int bufferLen = 65000;
    byte[] buffer = new byte[bufferLen];
    int count = 0;
    while ((count = parser.Files[0].Data.Read(buffer, 0, bufferLen)) > 0)
    {
         // save to output stream
         fs.Write(buffer, 0, count);
     }
     fs.Close();
}

We are very much in need of implementing you "StreamingMultipartFormDataParser" class, please help ...

**Comment by Vodurden** [comment]
Hi rajkumar,

Off the top of my head I would expect something like this:
```
using (var fs = new FileStream(...)) {
  var parser = new StreamingMultipartFormDataParser(InputFileStream);
  parser.FileHandler += (name, fileName, type, disposition, buffer, bytes) => {
    fs.Write(buffer, 0, bytes);
  }
  parser.StreamClosedHandler += () => fs.Close();
}
```

The code is obviously untested but the basic idea is that `FileHandler` will be called multiple times with a chunk of the file to write. We guarantee that it is called sequentially per-file so we can simply write it to the output.

**Comment by rajkumar-qsg** [comment]
Thank you for your reply. I tried implementing your code but I am getting this error "Operator '+=' cannot be applied to operands of type 'HttpMultipartParser.StreamingMultipartFormDataParser.FileStreamDelegate' and 'lambda expression'
"  at line `parser.FileHandler += (name, fileName, type, disposition, buffer, bytes) => {`

**Comment by Vodurden** [comment]
Hmm that's odd. You can see we use that exact syntax when implementing the `MultipartFormDataParser` (https://github.com/Vodurden/Http-Multipart-Data-Parser/blob/master/HttpMultipartParser/MultipartFormDataParser.cs#L209)

Maybe you're using an old C# version. Try giving the older delegate syntax a go:
```
using (var fs = new FileStream(...)) {
  var parser = new StreamingMultipartFormDataParser(InputFileStream);
  parser.FileHandler += delegate(string name, string fileName, string type, string disposition, byte[] buffer, int bytes) {
    fs.Write(buffer, 0, bytes);
  }
  parser.StreamClosedHandler += () => fs.Close();
  parser.Run();
}
```

It might be worth taking a look at https://msdn.microsoft.com/en-au/library/ms173176.aspx to see the delegate usage options available to you.

**Comment by rajkumar-qsg** [comment]
Thanks. Implementation worked but however the zip files uploaded are getting corrupt. Here is my code.

  ```
using (FileStream fs = new FileStream(HostingEnvironment.ApplicationPhysicalPath + "Uploads\\" + fileName1, FileMode.Create, FileAccess.ReadWrite, FileShare.ReadWrite))
            {
                 var parser = new StreamingMultipartFormDataParser(InputFileStream);


                 parser.FileHandler += (name, fileName, type, disposition, buffer, bytes) =>
                 {
                     fs.Write(buffer, 0, bytes);
                 };
                parser.StreamClosedHandler += () => fs.Close();

                parser.Run();
            }
```

**Comment by Vodurden** [comment]
Make sure only one zip file is being uploaded. If there are more you'll need to have multiple outgoing FileStreams, one per zip-file. Then you need to key them off the `name` parameter to ensure the correct data gets written.

**Comment by rajkumar-qsg** [comment]
Your solution worked and we could able to upload larger files than before.  We tried upto 1.60GB and it worked, but when we tried beyond 2 GB, it is not happening, we are not getting any error, but the file streaming is not started and the file is not even getting created in the destination.

We are actually using your solution to create a API to upload files.  API developed using WCF rest service.  We tried through poster (postman) and we have this problem.

Can you please provide us some help to fix this issue.  We are developing an API that should be capable of uploading upto 20GB.  Is our approach right?

**Comment by Vodurden** [comment]
Without an error or more context I'm not sure if I can help you. You need to start by checking what part of your upload pipeline is failing. If it never reaches the Streaming Multipart Parser code then there's not much I can do to help.

**Comment by rajkumar-qsg** [comment]
Hello, we have created an API for uploading large files and we are using your StreamingHttpMultiPartParser. We tried testing this API through poster (Postman) but postman crashes when file size greater than 2 GB is selected. We wanted to test this API before implementing in our Client. Is there any way you suggest for testing this API. 

Also, it will be great if you can share a sample C# code to upload a file through REST API using Multipart/form-data.

**Comment by rajkumar-qsg** [comment]
Hi, I have used your class in my API.  When i call the API method to upload a file using multipart/form data, i could able to upload files upto 2GB, beyond 2GB, i am receiving "Bad Request" error.  I just wanted to confirm from you if your class can be used to upload files beyond 2GB (very large files like 5GB and above)

I am trying to call the API through CURL, by using the CURL command generated from poster.  Working fine for upto 2GB files.  Please find the CURL command below:

**curl -X POST -H "FileName:5gb.rar" -H "Cache-Control: no-cache" -H "Postman-Token: e558ffba-f2db-43a1-338c-04e9b6cc2631" -H "Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW" -F "file=@D:\BigFilesForTesting\5gb.rar" "https://test-basefolder.com/ajspoc/upload.svc/UploadFile"**

**Comment by Vodurden** [comment]
It's been a while since I've used this library myself but I recall it didn't have any issues with files larger then 2GB. I suspect that the issue is elsewhere in the pipeline. If you can capture the exception that is causing the Bad Request that would help me identify if the library is at fault but without it I can't do much else to help you out.

Unfortunately I don't have the time to verify a 2GB parse myself but you could consider writing the multipart request to a file and piping it in as a FileStream into the StreamingHttpMultipartParser to see if it fails. That might help you figure out if it's the library or something else.
