### ISSUE TITLE
Improve .Net Standard support

### ISSUE THREAD

**Issue by Jericho** [Vodurden/Http-Multipart-Data-Parser#47]
I propose the following improvements:

- One single solution (instead of one for .NET 4.0 and another for `netcore`). This solution will produce both versions of the library.
- Target `net452` instead of `net40` since `net40`, `net45` and `net451` are no longer supported by Microsoft
- Target `netstandard` instead of `netcore` because `netcore` is intended for apps such as console apps for example while `netstandard` is intended for libraries. As it currently stands, a library targeting netstandard is prevented from using the HttpMultipartDataParser nuget package because it targets netcore.
- use xUnit for unit testing because it's multi-target friendly (meaning you write your unit tests only once and it will automatically run then against `net452` and `netstandard` versions automatically)

I recently implemented these improvements in my own library [StrongGrid](https://github.com/Jericho/StrongGrid). I now have a single solution which targets `net452` and `netstandard1.3` so I am familiar with what needs to be done. My motivation is that I would like to reference your library but I can't since you don't support `netstandard`.

**Comment by Jericho** [comment]
I forgot to mention: I would be happy to implement my suggestions and submit a PR.

**Comment by Vodurden** [comment]
Hi Jerichio

The proposed changes sound fantastic. I'm happy for you to submit a PR implementing them.

**Comment by Jericho** [comment]
Done, PR submitted.

**Comment by Vodurden** [comment]
Thanks Jericho, I've uploaded version 2.2.0 of the library here: https://www.nuget.org/packages/HttpMultipartParser/2.2.0

I'm going to close this now but please let me know if there are any issues and thanks for all the work!
