### ISSUE TITLE
Support for .Net 4.0

### ISSUE THREAD

**Issue by Bikeman868** [Vodurden/Http-Multipart-Data-Parser#54]
I want to use this package with .Net 4.0 but the latest NuGet package does not support it.
Is there an older version of the NuGet package that I can install?

**Comment by Vodurden** [comment]
One of the older versions might support .Net 4.0 but I can't guarantee that it'll work. Have a look at NuGet and try some of the 1.X version packages. 

Sorry for the months-late reply!

**Comment by K3UL** [comment]
Just a little comment to let any people arriving here that the last version compatible with 4.0 is 2.1.7
