### ISSUE TITLE
Couldn't install assembly to GAC

### ISSUE THREAD

**Issue by Savelich3k** [Vodurden/Http-Multipart-Data-Parser#57]
The latest 2.2.3 is not signed and doesn't have a strong name, so couldn't be installed to GAC. I have verified all versions below with ILSpy and found that the latest signed is 2.1.6 after which the project was migrated to NETCORE. I suspect that migration has a side effect of loosing signing. Please verify.

**Comment by jonreis** [comment]
I cannot sign my application that uses this library because it is not signed. Any chance on turning signing back on?

**Comment by Vodurden** [comment]
I've re-enabled signing with this commit: https://github.com/Vodurden/Http-Multipart-Data-Parser/commit/a9350c105b5baf00928d51fa3b83c64f3816b58c 

You're right that we lost signing with the transition to .NET core. I've just published [v2.2.4](https://www.nuget.org/packages/HttpMultipartParser/2.2.4) which should be correctly signed. 

I'm going to close this but if you find any issues around signing with 2.2.4 let me know and I'll re-open and investigate.
