### ISSUE TITLE
The given key 'name' was not present in the dictionary

### ISSUE THREAD

**Issue by maracuja-juice** [Vodurden/Http-Multipart-Data-Parser#67]
I am using a service which gives me responses in the following format:

```
--MIMEBoundary_db1ef2fb8e2d1f5a9c90f0eed9a482da52be09f800a0069e
Content-Type: text/xml; charset=utf-8
Content-Transfer-Encoding: binary
Content-ID: <0.eb1ef2fb8e2d1f5a9c90f0eed9a482da52be09f800a0069e@apache.org>

<?xml version="1.0" encoding="utf-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><response>1</response></soapenv:Body></soapenv:Envelope>
--MIMEBoundary_db1ef2fb8e2d1f5a9c90f0eed9a482da52be09f800a0069e
Content-Type: application/zip
Content-Transfer-Encoding: binary
Content-ID: <cb1ef2fb8e2d1f5a9c90f0eed9a482da52be09f800a0069e@apache.org>

PK
```

The `PK` would be the content of a zip file that I'm trying to load into a byte array.

I tried to use your package to that:

```
var stream = await response.Content.ReadAsStreamAsync();
var parser = new MultipartFormDataParser(stream);
FilePart zipFile = parser.Files.First();
```

When I try to do that I receive the following error though:

```
System.Collections.Generic.KeyNotFoundException: The given key 'name' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at HttpMultipartParser.StreamingMultipartFormDataParser.ParseParameterPart(Dictionary`2 parameters, RebufferableBinaryReader reader)
   at HttpMultipartParser.StreamingMultipartFormDataParser.ParseSection(RebufferableBinaryReader reader)
   at HttpMultipartParser.StreamingMultipartFormDataParser.Parse(RebufferableBinaryReader reader)
   at HttpMultipartParser.MultipartFormDataParser..ctor(Stream stream, String boundary, Encoding encoding, Int32 binaryBufferSize)
   at HttpMultipartParser.MultipartFormDataParser..ctor(Stream stream)
```

Is your package able to give me the byte array for the content in the second part of the response? If yes: What am I doing wrong?

**Comment by maracuja-juice** [comment]
I solved this now with a package that was published from Microsoft.

var responseAsMultipartContent = await response.Content.ReadAsMultipartAsync();
var zipContentStream = await responseAsMultipartContent.Contents[1].ReadAsStreamAsync();

**Comment by JulidaRocks** [comment]
I'm facing the same exception when trying

`MultipartFormDataParser parser = new MultipartFormDataParser(bindingContext.HttpContext.Request.Body);`

The Body contains a dto in json format and a pdf file.
The name of the IFormFile is set.

How can I solve this issue?

**Comment by maracuja-juice** [comment]
@JulidaRocks I wasn't able to use this package and now we use [this one](https://www.nuget.org/packages/microsoft.aspnet.webapi.client).
