### ISSUE TITLE
XPROJ is no longer supported

### ISSUE THREAD

**Issue by Jericho** [Vodurden/Http-Multipart-Data-Parser#68]
Have you considered upgrading the project files to the supported format so that we can open your project in VS.NET 2019?

If you are interested, I can submit a PR.

**Comment by Vodurden** [comment]
Hi Jericho,

I haven't looked in the project for some time and I don't really have a setup for releasing new changes as I'm no longer running Windows or spending much time in .NET

But I think it's fantastic that you've taken an interest in polishing up the project. If you're interested I'd be happy to give you write access to this Repo and NuGet so you can make the changes as you see fit.

What do you think?

**Comment by Jericho** [comment]
That would be great! I have a dependency on this project so I have a vested interest in making sure it’s maintained going forward.

**Comment by Vodurden** [comment]
@Jericho: I've added you as a collaborator to this repo :+1:

If you let me know what your NuGet username is then I'll give you access to the package as well

**Comment by Jericho** [comment]
My Nuget username is [jericho](https://www.nuget.org/profiles/Jericho).

**Comment by Vodurden** [comment]
@Jericho: Done! I've added you as an owner to the  HttpMultipartParser NuGet package. 

Good luck with everything, the enhancements you've posted so far look excellent :+1:

**Comment by Jericho** [comment]
Thanks. Invite accepted.
